### ISSUE TITLE
Issue opening website

### ISSUE THREAD

**Issue by frederikhors** [feugy/melodie#8]
https://feugy.github.io/melodie/ show only background image to me. Why?

**Comment by feugy** [comment]
Hi @frederikhors.

Would you mind telling me the browser (its version) you're using and your OS?
The site works fine on Firefox and chromium-based browsers (latest edge, chrome, chromium, opera).

![image](https://user-images.githubusercontent.com/186268/97799470-d0145980-1c2e-11eb-8707-f9a2158a74fd.png)

Now it may also be an issue with the language bundle. What is your system language please?

**Comment by frederikhors** [comment]
It works now.

**Comment by feugy** [comment]
It was the language support indeed.

Thanks a million for having reported it!

**Comment by frederikhors** [comment]
It's possible to use Melodie in the browser?

**Comment by feugy** [comment]
Unfortunately, not yet.

Mélodie is primary meant to organize and play local music files. Accessing (and watching) files from local drives is not really straight forward from the a browser.  

I don't have plans for it (I'd like first to release some native app), unless their is an important demand for it.
